### ISSUE TITLE
Use `gh auth setup-git` for authentication

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#38]
ref #30 

Dealing with tokens seems complicated. Delegating to an official tool that just needs a `GITHUB_TOKEN` var set is great!
gh is ALWAYS available on runners. Windows, macOS, and Ubuntu.

basically do

```sh
export GITHUB_TOKEN=...
gh auth setup-git

# This will automagically use the gh credentials from the $GITHUB_TOKEN!
# We use git's builtin credential manager to match a host (from github server URL) to a set of creds!
git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.wiki.git" /tmp/somewhere
```

**Comment by Andrew-Chen-Wang** [comment]
@jcbhmr can you clarify in the readme when a github token is needed to be specified? Whenever i see "github token" in a readme, i think of a PAT instead of the github action provided github token.

**Comment by jcbhmr** [comment]
@Andrew-Chen-Wang Yep! 👍
