### ISSUE TITLE
Update description to match readme

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#46]
<details>

![image](https://github.com/Andrew-Chen-Wang/github-wiki-action/assets/61068799/83aeb9eb-d866-4e9f-b65c-f40fb190da45)
![image](https://github.com/Andrew-Chen-Wang/github-wiki-action/assets/61068799/806d41cf-a55c-4405-b6db-609ca3953674)

also might wanna tweak those tags too 😉

**Comment by jcbhmr** [comment]
track in the milestone #30 issue, not here 😬

**Comment by jcbhmr** [comment]
reopening because it's not changed yet 😁
![image](https://github.com/Andrew-Chen-Wang/github-wiki-action/assets/61068799/19c8e4cf-b449-458f-b47e-3a547ab8c91d)

**Comment by Andrew-Chen-Wang** [comment]
lemme know what desc and tags you'd like

**Comment by jcbhmr** [comment]
I'd _recommend_ the description match the readme's tagline thing right beneath the `<h1>`. In this case, that's:
> 📖 GitHub Action to sync a folder to the GitHub wiki

For tags, I'd _recommend_ the following, but really **anything is great!**
> bash wiki actions github-actions github-action github-wiki

**Comment by jcbhmr** [comment]
@Andrew-Chen-Wang friendly ping 📬

**Comment by Andrew-Chen-Wang** [comment]
Done
