### ISSUE TITLE
Clarify GitHub auto-token vs GitHub PAT

### ISSUE THREAD

**Issue by jcbhmr** [Andrew-Chen-Wang/github-wiki-action#52]
> @jcbhmr can you clarify in the readme when a github token is needed to be specified? Whenever i see "github token" in a readme, i think of a PAT instead of the github action provided github token.

_Originally posted by @Andrew-Chen-Wang in https://github.com/Andrew-Chen-Wang/github-wiki-action/issues/38#issuecomment-1552185948_

**Comment by jcbhmr** [comment]
![image](https://github.com/Andrew-Chen-Wang/github-wiki-action/assets/61068799/01755187-78c5-4c66-8e73-715e3c4be055)

![image](https://github.com/Andrew-Chen-Wang/github-wiki-action/assets/61068799/7dc08039-b5c3-4903-8f67-83b2dba4ba43)

I can try to use "`${{ github.token }}`" or "GitHub context token" or "GitHub auto-token" in these cases 👆 but I don't know how much good it would do since most of the text there is instructions on how to replace the `${{ github.token }}` with your own Personal Access Token for cross-repo pushing permissions. I could elaborate on that and name the section something better like:

> ### Cross-repo wikis
>
> You _can_ use this action to deploy your octocat/mega-docs repository to the octocat/mega-project repository's wiki tab! You just need to:
>
> 1. Create a custom GitHub Personal Access Token with the permissions to push to the octocat/mega-project repository. That's the target repo where your wiki pages will be pushed to the `.wiki.git`.
> 2. In the octocat/mega-docs repo (the source code for the wiki), you need to set the `repository:` option to `repository: octocat/mega-project` to tell the action to push there.
> 3. You need to set the `token:` option to the Personal Access Token that you created with the ability to push to the wiki Git repo. You can use repository secrets for this! Something like `token: ${{ secrets.MY_TOKEN }}` is good!
>
> Here's an example:
> 
> _{{and then a demo here}}_

And then I could also put in a section about permissions like:

> ### Permissions
>
> In order to successfully push to the `.wiki.git` Git repository that backs the wiki tab, we need the `contents: write` permission. You can set this like so:
>
> _{{and then a demo here}}_

Does that seem like what you had in mind?

**Comment by Andrew-Chen-Wang** [comment]
I usually refer to github.token as "Auto-included GitHub Action token"

I meant a distinction between when to use this action token and when to use a PAT.
