### ISSUE TITLE
Add a note that version 4.3.0 needs to be used to get working links in the Wiki

### ISSUE THREAD

**Issue by softworkz** [Andrew-Chen-Wang/github-wiki-action#75]
....this would have saved me the time to find out.

PS: Thanks for the project!

**Comment by Andrew-Chen-Wang** [comment]
Hi we should definitely maintain a changelog; otherwise, i think new/returning users who find the changelog should suffice.

**Comment by softworkz** [comment]
The changelog doesn't make it clear that 4.3 performs link replacement and 4.4 not.
That was my point  :-)

**Comment by Andrew-Chen-Wang** [comment]
Ah let me clarify! We don't even have a CHANGELOG file lol. I meant I'll make one to make sure we're documenting our changes properly 😅

**Comment by softworkz** [comment]
Ah, got it now - sounds good!
